/* Sports List */
TRUNCATE sports;

INSERT INTO sports (name) VALUES
('Baseball'),
('Basketball'),
('Bowling'),
('Cheerleading'),
('Cross Country'),
('Equestrian'),
('Fencing'),
('Field Hockey'),
('Football'),
('Golf'),
('Gymnastics'),
('Ice Hockey'),
('Lacrosse'),
('Rifle'),
('Rowing'),
('Rugby'),
('Sailing'),
('Skiing'),
('Soccer'),
('Softball'),
('Squash'),
('Swimming & Diving'),
('Tennis'),
('Track Indoor'),
('Track Outdoor'),
('Volleyball'),
('Water Polo'),
('Wrestling'),
('Badminton'),
('Powerlifting'),
('BodyBuilding'),
('MMA'),
('Karate'),
('Judo'),
('Tactical');